### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by sergeevabc** [FaVorith/recursive-virustotal#1]
``` console
$ ver && python -V
Microsoft Windows [Version 6.1.7601]
Python 3.8.8

$ pip install virustotal-api
Collecting virustotal-api                                                                                                                     
  Downloading virustotal_api-1.1.11-py2.py3-none-any.whl (15 kB)                                                                              
Requirement already satisfied: requests>=2.22.0 in c:\python\lib\site-packages (from virustotal-api) (2.24.0)                                 
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python\lib\site-packages (from requests>=2.22.0->virustotal-api) (3.0.4)               
Requirement already satisfied: idna<3,>=2.5 in c:\users\alexander\appdata\roaming\python\python38\site-packages (from requests>=2.22.0->virust
otal-api) (2.9)                                                                                                                               
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python\lib\site-packages (from requests>=2.22.0->virustotal-api) 
(1.25.8)                                                                                                                                      
Requirement already satisfied: certifi>=2017.4.17 in c:\python\lib\site-packages (from requests>=2.22.0->virustotal-api) (2019.11.28)         
Installing collected packages: virustotal-api                                                                                                 
Successfully installed virustotal-api-1.1.11                                                                                                  

$ python recursive-vt.py
Traceback (most recent call last):         
  File "vt.py", line 13, in <module>       
    import yaml                            
ModuleNotFoundError: No module named 'yaml'

```

**Comment by FaVorith** [comment]
Hi @sergeevabc , thank you for your feedback and for reporting the issue.

It looks to me that you are missing the Yaml package. Sorry that I did not mention this requirement separately.
If you are using the pip installer, could you please try the following:

_pip install PyYAML_

(also see: https://pypi.org/project/PyYAML/)

Please let me know how this goes. If this works for you, I'll extend the documentation accordingly.

Cheers,
Fabian

**Comment by sergeevabc** [comment]
With PyYAML it works, indeed. But works not as expected. I put `recursive-vt.py` in `C:\Python\Scripts\`, run there, it creates `config.yaml`, but later, when I run it from another folder (it is possible since `C:\Python\Scripts\` is within PATH variable), it creates configuration file again in that another folder.

**Comment by FaVorith** [comment]
Hi @sergeevabc ,

Thank you very much for your feedback. I added the description for the PyYAML installation to the setup instructions to make it easier for future users.

Regarding the creation of the config file in different locations, what you are observing is that the script is putting the file into the current working directory, while you would want to have the file in the script's original folder.

I agree with you that this makes more sense and I adjusted the script accordingly. Please check if the new version works for you as expected. If not, I would consider this a separate issue, which is why for now I'm closing the current one.

Thank you very much for your time and feedback and all the best in your threat hunting!

Cheers,
Fabian
